ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
#ribbon:
#      listOfServers: 192.168.40.251:8282
#请求连接的超时时间
#  ConnectTimeout: 250
# 请求处理的超时时间
#  ReadTimeout: 1000
#  # 对所有操作请求都进行重试
#  OkToRetryOnAllOperations: true
#  # 切换实例的重试次数
#  MaxAutoRetriesNextServer: 2
#  # 对当前实例的重试次数
#  MaxAutoRetries: 1

logging:
  level:
    root: WARN
  path: ./logs/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
          #断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试
            timeoutInMilliseconds: 100000